# Generated by Django 5.2.4 on 2025-07-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Division', '0002_person_birth_date_person_hire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='people_photos/', verbose_name='Фотография'),
        ),
    ]
